// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAln2RnsrJhcxhD-LZpjOP-cmG63qWNW-k',
    appId: '1:712605391861:web:4118b4742cac916322debc',
    messagingSenderId: '712605391861',
    projectId: 'pikpo-video-conference',
    authDomain: 'pikpo-video-conference.firebaseapp.com',
    storageBucket: 'pikpo-video-conference.appspot.com',
    measurementId: 'G-1H1VCRJLK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKP0CDQxHdpUSZOEMVsOkCwwa1hMlbrK0',
    appId: '1:712605391861:android:2ecc4d73ca2e7dad22debc',
    messagingSenderId: '712605391861',
    projectId: 'pikpo-video-conference',
    storageBucket: 'pikpo-video-conference.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvSVGq6CeWaSwe6kNj60bsfOFHiqj_D1s',
    appId: '1:712605391861:ios:b422c67edfd2baee22debc',
    messagingSenderId: '712605391861',
    projectId: 'pikpo-video-conference',
    storageBucket: 'pikpo-video-conference.appspot.com',
    iosBundleId: 'com.example.pikpoVideoConference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvSVGq6CeWaSwe6kNj60bsfOFHiqj_D1s',
    appId: '1:712605391861:ios:b422c67edfd2baee22debc',
    messagingSenderId: '712605391861',
    projectId: 'pikpo-video-conference',
    storageBucket: 'pikpo-video-conference.appspot.com',
    iosBundleId: 'com.example.pikpoVideoConference',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAln2RnsrJhcxhD-LZpjOP-cmG63qWNW-k',
    appId: '1:712605391861:web:e089b2de1bf4710822debc',
    messagingSenderId: '712605391861',
    projectId: 'pikpo-video-conference',
    authDomain: 'pikpo-video-conference.firebaseapp.com',
    storageBucket: 'pikpo-video-conference.appspot.com',
    measurementId: 'G-CTBQK8QB34',
  );
}
